Python 3.14.0 (tags/v3.14.0:ebf955d, Oct  7 2025, 10:15:03) [MSC v.1944 64 bit (AMD64)] on win32
Enter "help" below or click "Help" above for more information.
>>> from flask import Flask, request, jsonify
... import subprocess, uuid, os
... 
... app = Flask(__name__)
... 
... @app.route("/run", methods=["POST"])
... def run_cpp():
...     code = request.json["code"]
... 
...     file_id = str(uuid.uuid4())
...     cpp_file = f"{file_id}.cpp"
...     exe_file = f"{file_id}.out"
... 
...     with open(cpp_file, "w") as f:
...         f.write(code)
... 
...     try:
...         subprocess.run(["g++", cpp_file, "-o", exe_file],
...                        check=True, stderr=subprocess.STDOUT)
... 
...         output = subprocess.check_output([f"./{exe_file}"],
...                                          stderr=subprocess.STDOUT).decode()
... 
...     except subprocess.CalledProcessError as e:
...         output = e.output.decode() if e.output else str(e)
... 
...     if os.path.exists(cpp_file): os.remove(cpp_file)
...     if os.path.exists(exe_file): os.remove(exe_file)
... 
...     return jsonify({"output": output})
... 
... 
... app.run(host="0.0.0.0", port=5000)
